# maxIndependentSet: MaximumIndependentSetOfForest.o
# 	g++ -o maxIndependentSet MaximumIndependentSetOfForest.cpp

maxWeightIndependentSet: MaximumWeightIndependentSetOnTree.o
	g++ -o maxWeightIndependentSet MaximumWeightIndependentSetOnTree.cpp