DecompositionTree: DecompositionTree.cpp
	g++ -o DecompositionTree DecompositionTree.cpp ./lib/dNode.cpp ./lib/dTree.cpp ./lib/graph.cpp ./lib/utils.cpp

RandomTree: RandomTree.cpp
	g++ -o RandomTree RandomTree.cpp